// angular-starter/starter-project/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'starter-project';
}

<div class="card flex flex-column align-items-center justify-content-center">
  <h1>Prime Starter Projects</h1>
  <p-button label="Check" icon="pi pi-check"></p-button>
</div>

// vite-react-starter/src/App.jsx
import { useState } from 'react';
import { Button } from 'primereact/button';
function App() {
  return (
    <>
      <div className='card flex flex-column align-items-center py-4 justify-content-center'>
        <h1>Prime React Starter Project (OCEM Sandbox)</h1>
        <Button label='Check' icon='pi pi-check' />
      </div>
    </>
  );
}

export default App;
