// vite-react-starter/src/App.jsx
import { useState } from 'react';
import { Button } from 'primereact/button';
function App() {
  return (
    <>
      <div className='card flex flex-column align-items-center py-4 justify-content-center'>
        <h1>Prime React Starter Project (OCEM Sandbox)</h1>
        <Button label='Check' icon='pi pi-check' />
      </div>
    </>
  );
}

export default App;

// angular-demo/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  title = 'angular-demo';

  ngOnInit(): void {
    console.log('App Component');
    console.log('Angular 15 Demo Component');
    console.log('Hi Team , Getting Record Screen By OBS Screen Recorder');
  }
}

<div
  class="card flex flex-column align-items-center justify-content-center py-4"
>
  <h1>Angular Work Shop</h1>
  <p-button label="Check" icon="pi pi-check"></p-button>
</div>

<h1 class="text-xl text-center">Hello World App by Team unsplash</h1>
