// angular-starter/starter-project/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'starter-project';
}

<div class="card flex flex-column align-items-center justify-content-center">
  <h1>Prime Starter Projects</h1>
  <p-button label="Check" icon="pi pi-check"></p-button>
</div>

// vite-react-ecom/src/App.jsx
import { useState } from 'react';
import { Camera } from 'lucide-react';
import Icon from '../components/Icon';
import * as Prime from '../config/PrimeConfig';
import LandingPage from '../pages/LandingPage';

function App() {
  return (
    <>
      <LandingPage />
      {/* <div className='container'>
        <div className='card flex gap-4 p-4 justify-content-center'>
          <h1>Hello World App</h1>
          <Prime.Button label='Check' icon='pi pi-check' />
          <Camera color='red' size={48} />;
          <Icon name={'Home'} size={48} color={'green'} />
        </div>
      </div> */}
    </>
  );
}

export default App;
