// vite-react-starter/src/App.jsx
import { useState } from 'react';
import * as Prime from '../config/PrimeConfig';
function App() {
  const header = (
    <img
      alt='Card'
      src='https://primefaces.org/cdn/primereact/images/usercard.png'
    />
  );
  const footer = (
    <>
      <Prime.Button label='Save' icon='pi pi-check' />
      <Prime.Button
        label='Cancel'
        severity='secondary'
        icon='pi pi-times'
        style={{ marginLeft: '0.5em' }}
      />
    </>
  );

  return (
    <>
      <div className='card flex flex-column align-items-center py-4 justify-content-center'>
        <h1>Prime React Starter Project (OCEM Sandbox)</h1>
        <Prime.Button label='Check' icon='pi pi-check' />
      </div>

      <div className='card flex justify-content-center py-2'>
        <Prime.Card
          title='Title'
          subTitle='Subtitle'
          footer={footer}
          header={header}
          className='md:w-25rem'
        >
          <p className='m-0'>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore
            sed consequuntur error repudiandae numquam deserunt quisquam
            repellat libero asperiores earum nam nobis, culpa ratione quam
            perferendis esse, cupiditate neque quas!
          </p>
        </Prime.Card>
      </div>
    </>
  );
}

export default App;

// ang-bootstrap/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'ang-bootstrap';
  value2:any
}

<header>
  <!-- <nav class="navbar navbar-dark  navbar-expand-lg bg-dark ">
    <div class="container">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link ">Link 2</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav> -->
  <nav class="navbar navbar-dark navbar-expand-lg bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="#">
        <img
          src="https://getbootstrap.com/docs/5.1/assets/brand/bootstrap-logo.svg"
          alt=""
          srcset=""
          width="30"
          height="24"
          class="d-inline-block align-text-top"
        />
        Bootstrap
      </a>
      <button
        class="navbar-toggler shadow-none"
        type="button"
        data-bs-toggle="offcanvas"
        data-bs-target="#offcanvasNavbar"
        aria-controls="offcanvasNavbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Sidebar -->
      <div
        class="sidebar offcanvas offcanvas-end"
        tabindex="-1"
        id="offcanvasNavbar"
        aria-labelledby="offcanvasNavbarLabel"
      >
        <div class="offcanvas-header text-white border-bottom">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
          <button
            type="button"
            class="btn-close text-reset btn-close-white shadow-none"
            data-bs-dismiss="offcanvas"
            aria-label="Close"
          ></button>
        </div>
        <div class="offcanvas-body d-flex flex-column flex-lg-row p-2">
          <ul class="navbar-nav justify-content-center flex-grow-1 pe-3">
            <li class="nav-item mx-2">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item mx-2">
              <a class="nav-link" href="#hello">Hello</a>
            </li>
            <li class="nav-item mx-2">
              <a class="nav-link" href="#">Products</a>
            </li>
            <li class="nav-item mx-2">
              <a class="nav-link" href="#">Service Location</a>
            </li>
            <li class="nav-item mx-2">
              <a class="nav-link" href="#">Pay Now</a>
            </li>

          </ul>
          <form class="d-flex" role="search">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-success" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </div>
  </nav>
</header>

<section
  class="bg-dark text-light p-5 rounded-1 d-flex h-100 align-items-center justify-content-center"
>
  <div class="container">
    <h1 class="display-1">
      Angular Bootstrap Starter Project
      <i class="bi-alarm" style="color: cornflowerblue"></i>
    </h1>
  </div>
</section>

<section class="h-100 bg-info text-light p-5 rounded-1 d-flex h-100 align-items-center justify-content-center" id="hello">
<h1 class="display-1 fw-bold ">Hello World App</h1>
</section>

<section class="h-100 bg-light   text-dark  p-5 rounded-1 d-flex h-100 align-items-center justify-content-center">
  <div class="d-flex align-items-center gap-4   justify-content-center">
    <div class="spinner-border" role="status" >
      <span class="sr-only fs-1 " id="loading"></span>
    </div>
    <i class="pi pi-check fs-1"></i>
    <p-button label="Check" class="rounded-1 " icon="pi pi-check"></p-button>
    <p-card header="Title">
      <p class="m-0">
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore sed consequuntur error repudiandae numquam deserunt quisquam repellat libero asperiores earum nam nobis, culpa ratione quam perferendis esse, cupiditate neque
          quas!
      </p>
  </p-card>
  <span class="p-input-icon-right">
    <i class="pi pi-spin pi-spinner"></i>
    <input type="text" pInputText [(ngModel)]="value2" />
</span>
  </div>
</section>
